In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[-0.07081988  1.54618823 -0.11823879  0.25852273  0.39903314]


In [2]:
# Here, the vector a is what they call a rank 1 array in numpy. This is bad
# You can tell its a rank 1 array because there is nothing after the comma
print(a.shape)

(5,)


In [5]:
# Lots of unintuitive things happen when you use rank 1 arrays

# The transpose of a rank 1 array is the exact same
print(a.T)

# One might expect this to output a matrix, but it does not.
print(np.dot(a, a.T))

[-0.07081988  1.54618823 -0.11823879  0.25852273  0.39903314]
2.63575535823


In [12]:
# These errors can be fixed by giving your vectors a formal shape when you make them:
a = np.random.randn(5, 1)
print(a.shape)
print
print(a)
print
print(a.T)
print
print(a.dot(a.T))

# You can tell a now is not a rank 1 array because when you print it out, it has 2 sets of square brackets
# Also, when you print out the shape, there is not a floating comma

(5, 1)

[[-2.33868612]
 [-0.24153268]
 [-0.46302135]
 [ 0.26893422]
 [-1.14516854]]

[[-2.33868612 -0.24153268 -0.46302135  0.26893422 -1.14516854]]

[[ 5.46945277  0.56486913  1.08286162 -0.62895273  2.67818978]
 [ 0.56486913  0.05833804  0.11183479 -0.0649564   0.27659563]
 [ 1.08286162  0.11183479  0.21438878 -0.12452229  0.53023749]
 [-0.62895273 -0.0649564  -0.12452229  0.07232561 -0.30797501]
 [ 2.67818978  0.27659563  0.53023749 -0.30797501  1.31141099]]
